# elasticsearch
spring:
  data:
    elasticsearch:
      cluster-name: travelkeeper-cluster-dev
      cluster-nodes: 10.0.2.2:9300
      #cluster-nodes: localhost:9300
      sort-by: id
      index: travelkeeper
      type:
        location: location

# google drive api
google:
  #application-name: travelkeeper
  #service-account-email: travelkeeper@travelkeeper-216714.iam.gserviceaccount.com
  folder: 1YjI3lVAPzhbGlKjaJjKbC2lBoVrMp-s-
  #service-account-key: credentials.p12
  #service-account-private-key: notasecret

# pagination
pagination:
  pagesize: 10

# log
logging:
  level:
    root: INFO
    com.travelkeeper: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
