# elasticsearch
spring:
  data:
    elasticsearch:
      cluster-name: travelkeeper-cluster-dev
      cluster-nodes: 10.0.2.2:9300
      #cluster-nodes: localhost:9300
      sort-by: id
      index: travelkeeper
      type:
        location: location

# firebase
firebase:
  credentials-path: credentials/firebase_secret.json
  database:
    url: https://travelkeeper-b2bb8.firebaseio.com

# pagination
pagination:
  pagesize: 10

# log
logging:
  level:
    root: INFO
    com.travelkeeper: DEBUG
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
