# elasticsearch
spring:
  data:
    elasticsearch:
      cluster-name: travelkeeper-cluster
      cluster-nodes: localhost:9300
      sort-by: id
      index: travelkeeper
      type:
        location: location

# pagination
pagination:
  pagesize: 10

# log
logging:
  level:
    root: INFO
    com.travelkeeper: INFO
    org.springframework: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n"
